<a href="https://colab.research.google.com/github/igorsavinkin/ChromeCrawlerWildSpider/blob/master/distance_manhattan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
m=np.array([[1,1,0],[0,2,-1],[2,3,1],[1,0,4]])
m

array([[ 1,  1,  0],
       [ 0,  2, -1],
       [ 2,  3,  1],
       [ 1,  0,  4]])

In [2]:
n=len(m)
r=np.zeros((n,n))
for i in range(n):
  for j in range(n):
    r[i][j]=sum(abs(m[i]-m[j]))
r

array([[0., 3., 4., 5.],
       [3., 0., 5., 8.],
       [4., 5., 0., 7.],
       [5., 8., 7., 0.]])

In [3]:
sum(r)

array([12., 16., 16., 20.])